# Generated by Django 3.2.5 on 2021-07-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
