# Generated by Django 3.2.5 on 2021-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_category_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Student'),
        ),
    ]
